Add grunt step to build

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -61,6 +61,50 @@ if [ -f www/composer.json ] && [ ! -d www/vendor ]; then
     export GIT_DIR=$GIT_DIR_ORIG
 fi
 
+
+#now we're going to run grunt to perform the client side build
+# install dependencies with npm
+function run_npm() {
+  command="$1"
+  
+  [ ! -z $VERBOSE ] && command="--verbose $command"
+
+  cd $BUILD_DIR
+  HOME="$BUILD_DIR" $VENDORED_NODE/bin/node $VENDORED_NPM/cli.js $command 2>&1 | indent
+
+  if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+echo " ! Failed to $command dependencies with npm"
+    if [ ! -z $BUILDPACK_RETRY_VERBOSE ]; then
+echo " ! Relaunching the command in verbose mode to help debugging"
+      run_npm "--verbose $command"
+    fi
+exit 1
+  fi
+}
+
+
+
+echo "-----> Installing dependencies with npm"
+#run_npm "install --production"
+run_npm "install"
+run_npm "rebuild"
+echo "Dependencies installed" | indent
+
+echo "-----> Building runtime environment"
+mkdir -p $BUILD_DIR/.profile.d
+echo "export PATH=\"\$HOME/bin:\$HOME/node_modules/.bin:\$PATH\"" > $BUILD_DIR/.profile.d/nodejs.sh
+
+if [ -f $BUILD_DIR/grunt.js ] || [ -f $BUILD_DIR/Gruntfile.js ] || [ -f $BUILD_DIR/Gruntfile.coffee ]; then
+  # make sure that grunt and grunt-cli are installed locally
+  run_npm "install grunt-cli"
+  run_npm "install grunt"
+  echo "-----> Found Gruntfile, running grunt heroku:$NODE_ENV task"
+  $BUILD_DIR/node_modules/.bin/grunt heroku:$NODE_ENV
+else
+  echo "-----> No Gruntfile (grunt.js, Gruntfile.js, Gruntfile.coffee) found"
+fi
+
+
 cat >>boot.sh <<EOF
 for var in \`env|cut -f1 -d=\`; do
   echo "PassEnv \$var" >> /app/apache/conf/httpd.conf;
